- name: extract files
  become: true
  unarchive:
    src: files/artifact.tar.gz
    dest: /home/ubuntu
- name: start app
  become: true
  shell: cd /home/ubuntu/
    npm install
    pm2 stop default
    pm2 start npm -- start
